### ISSUE TITLE
Server screen log is spammed with messages

### ISSUE THREAD

**Issue by LyndonL37** [Tristan-dvr/ServerRestart#2]
I'm not sure if I've missed a setting somewhere, but I'm getting spammed in the server window with messages every 60 seconds.
Is there any way to reduce this log message to hourly or something?

![image](https://github.com/Tristan-dvr/ServerRestart/assets/141901074/67cc5f1b-8493-4b46-9d63-e30410815490)

**Comment by Tristan-dvr** [comment]
Hi. I afraid there is currently no way to disable these logs or reduce them.
But its good idea to add this to the settings

**Comment by LyndonL37** [comment]
Awesome, thanks 👍

**Comment by Tristan-dvr** [comment]
Ive beed added configuration option to completely disable or edit period of these logs. Check out the latest version
