### ISSUE TITLE
Latest Hildir's Request update seems to have broken the plugin

### ISSUE THREAD

**Issue by LyndonL37** [Tristan-dvr/ServerRestart#3]
FYI - the restart isn't occurring anymore since the latest content drop:

![image](https://github.com/Tristan-dvr/ServerRestart/assets/141901074/9015412c-1114-482a-9138-7727156fecc3)

**Comment by LyndonL37** [comment]
Further info when I restarted the server manually might be of use:

![image](https://github.com/Tristan-dvr/ServerRestart/assets/141901074/f9ee5ca8-d537-44fa-ae0d-ffe65ef36141)

**Comment by Tristan-dvr** [comment]
It was fixed today. Updated plugin is already available on thunderstore
